#!/bin/bash
# private bashrc, to be sourced by the .bashrc. 
# DO NOT change the default .bashrc, it's better to import private
# update: 2014.03.25
# logs: Add some personal configuration

#export:
export PS1="[\[\033[01;51m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]]\$"


# alias begin: 
alias	..="cd .."
alias   ls="ls -Gh"
alias   la="ls -Ghal"
alias   ll="ls -Ghl"

#alias end.

if [[ `uname` == "Darwin" ]]; then
    autossh -M 1081 -D 1080 -i /Users/w/.ssh/identification -qNnt 54b5fcb35973cab7770002e0@python-mfrc531.rhcloud.com 2>/var/log/proxy-err.log &
fi

